services:
  - type: web
    name: agentiq-vfo-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: agentiq-vfo-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
    buildFilter:
      paths:
      - backend/**
  - type: web
    name: agentiq-vfo-frontend
    env: node
    rootDir: frontend
    buildCommand: "rm -rf node_modules package-lock.json && npm install && npm run build"
    startCommand: "npm run serve"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_BASE_URL
        value: "https://agentiq-vfo-backend.onrender.com"
    buildFilter:
      paths:
      - frontend/**

databases:
  - name: agentiq-vfo-db
    databaseName: vfo_db
    user: user 