name: security

on:
  push:
  pull_request:

jobs:
  py-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt pip-audit bandit
      - name: Bandit (backend)
        run: bandit -r backend/app
      - name: pip-audit (backend)
        run: pip-audit -r backend/requirements.txt

  node-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install frontend
        run: cd frontend && npm ci
      - name: npm audit (prod)
        run: cd frontend && npm audit --omit=dev

  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          path: '.'

